export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_UPDATE = "USER_UPDATE";
export const UPDATE_ERROR = "UPDATE_ERROR";

export const LAUNDRY_LOADED = "LAUNDRY_LOADED";
export const LAUNDRY_ERROR = "LAUNDRY_ERROR";
export const LAUNDRY_UPDATE = "LAUNDRY_UPDATE";

export const PAYMENT_LOADED = "PAYMENT_LOADED";
export const PAYMENT_ERROR = "PAYMENT_ERROR";
// export const PAYMENT_DELETE = "PAYMENT_DELETE";
// export const PAYMENT_ADD = "PAYMENT_ADD";

export const PACKAGE_LOADED = "PACKAGE_LOADED";
export const PACKAGE_ERROR = "PACKAGE_ERROR";

export const CUSTOMER_LOADED = "CUSTOMER_LOADED";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";

export const TRANSACTION_LOADED = "TRANSACTION_LOADED";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";